extends: spectral:oas

rules:
  # Autoriser OpenAPI 3.1 tout en vérifiant références
  openapi-tags: off
  operation-tags: off
  info-contact: off
  info-description: warn
  operation-description: warn
