// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import './lib/config/env.js'
import process from 'node:process'
import {defineConfig} from 'prisma/config'

function getDatabaseUrl(): string | undefined {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-return
  return process.env.DATABASE_URL
}

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: getDatabaseUrl()
  }
})
