// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import './lib/config/env.js'
import {defineConfig} from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: process.env.DATABASE_URL
  }
})
