node scripts/import-zones.js
node scripts/blv/irrigants-aquasys/import-point-prelevements.js
node scripts/blv/irrigants-aquasys/import-declarants.js
node scripts/blv/irrigants-aquasys/import-exploitations.js
node scripts/blv/irrigants-aquasys/create-ougc-account.js
node scripts/blv/irrigants-aquasys/import-volumes.js
node scripts/blv/template-files/import-point-prelevements.js
node scripts/blv/template-files/import-declarants.js
node scripts/blv/template-files/import-exploitations.js
node scripts/blv/template-files/import-volumes.js
node scripts/blv/industriels-icpe-gidaf/import-point-prelevements.js
node scripts/blv/industriels-icpe-gidaf/import-declarants.js
node scripts/blv/industriels-icpe-gidaf/import-exploitations.js
node scripts/blv/industriels-icpe-gidaf/create-gidaf-account.js
node scripts/blv/industriels-icpe-gidaf/import-volumes.js
node scripts/blv/import-instructors.js
node scripts/blv/import-instructor-zones.js
