name: OpenAPI Lint

on:
  pull_request:
    paths:
      - 'docs/openapi.yaml'
      - '.spectral.yaml'
      - 'package.json'
  push:
    branches: [ main, improve-timeseries ]
    paths:
      - 'docs/openapi.yaml'
      - '.spectral.yaml'
      - 'package.json'

jobs:
  spectral:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint OpenAPI spec
        run: npm run lint:openapi
